# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/648a6b81-e1c9-41a9-b448-ce8c37844ce7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos-crypt" = {
	device = "/dev/disk/by-uuid/f5d8351e-4239-4ae7-84e8-37576ea87147";
	preLVM = false;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ED26-A419";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
